# Labels for swirl Ukrainian/English activation system

activate_labels <- list(
  uk = list(
    start = "🇺🇦 Активація української мови для swirl... 🇺🇦\n\n",
    available_options = "\nДоступні опції?\n",
    option_continue = "1) Продовжити\n",
    option_install = "2) Встановити\n",
    option_delete = "3) Видалити\n",
    option_update_installed = "4) Оновити встановлений курс\n",
    enter_choice = "Введіть номер (1/2/3/4) та натисніть ENTER: ",
    enter_choice_simple = "Введіть номер та натисніть ENTER: ",
    delete_prompt = "Бажаєте видалити локальні курси swirl?\n",
    yes = "1) Так\n",
    no_continue = "2) Повернутися\n",
    no_courses = "ℹ️ Локальні курси не знайдено.\n",
    select_delete = "\nОберіть курс для видалення:\n",
    continue = "Повернутися",
    deleted = "  🗑️ Видалено курс: ",
    invalid = "⛔ Невірний вибір. Спробуйте ще раз.\n",
    skip_delete = "⏩ Пропущено видалення курсів.\n",
    install_prompt = "\nЧи бажаєте встановити локальний курс swirl?\n",
    yes_install = "1) Так\n",
    no_install = "2) Повернутися\n",
    random_install = "3) Встановити рандомний курс\n",
    available_courses = "\nℹ️ Доступні курси з папки swirl-courses:\n",
    enter_number_or_manual = "Оберіть курс для встановлення за номером, %d для ручного вводу, або %d для рандомного курсу: ",
    manual_course = "Введіть назву курсу (name_of_course): ",
    random_course = "Встановити рандомний курс",
    not_found = "Не знайдено локальних курсів. Введіть назву курсу вручну (name_of_course): ",
    not_found_folder = "Не знайдено локальної папки swirl-courses. Введіть назву курсу вручну (name_of_course): ",
    installing = "\nℹ️ Встановлюю курс із директорії: ",
    installed = "✓ Курс '%s' успішно встановлено і завантажено!\n",
    not_exist = "❌ Директорія курсу '%s' не існує!\n",
    install_next = "\nЩо бажаєте зробити далі?\n1) Встановити ще курс\n2) Повернутися\n",
    packages_missing = "\n❗ Необхідні пакети не встановлені:\n   ",
    packages_action = "Виберіть дію:\n1) Встановити пакети\n2) Продовжити без встановлення\n",
    packages_install_cmd = "\n📦 Для встановлення пакетів виконайте:\ninstall.packages(c(%s))\n",
    packages_next = "Введіть 'next()' після завершення встановлення пакетів: ",
    packages_success = "✓ Всі необхідні пакети встановлені!\n",
    packages_skipped = "⚠️ Ви продовжили без встановлення пакетів swirl.\nДеякі функції можуть бути недоступні.\n",
    swirl_loaded = "✓ Пакет swirl завантажено\n",
    swirl_not_installed = "❌ Пакет swirl не встановлений, не можу продовжити!\n",
    translation_choose = "\nЯку версію перекладу бажаєте активувати?\n1) Тільки українські фрази (ukrainian_phrases_only)\n2) Повна українізація (ukrainian_full_translation)\n3) Залишити оригінал (без перекладу)\n",
    translation_enter = "Введіть номер (1/2/3) та натисніть ENTER: ",
    only_phrases = "\n🔄 Активую тільки українські фрази...\n",
    only_phrases_ok = "✓ Українські фрази активовано!\n",
    only_phrases_fail = "❌ Помилка активації українських фраз: ",
    full_translation = "\n🔄 Активую повну українізацію...\n",
    pick_course = "Оберіть курс (лише встановлені у swirl):\n",
    exit = "Вийти",
    course_number = "Введіть номер курсу: ",
    invalid_course = "Невірний вибір курсу",
    pick_lesson = "\nОберіть урок (лише встановлені у swirl):\n",
    lesson_number = "Введіть номер уроку: ",
    invalid_lesson = "Невірний вибір уроку",
    not_found_local = "Локальна копія уроку не знайдена: ",
    no_yaml = "Немає .yaml в обраному уроці\n",
    only_lesson_yaml = "У цьому уроці є лише lesson.yaml. Немає додаткових YAML-файлів для активації.\n",
    pick_yaml = "\nОберіть .yaml файл для активації:\n",
    yaml_number = "Введіть номер .yaml: ",
    invalid_yaml = "Невірний вибір yaml. Вихід без змін.\n",
    confirm_selection = "\nВи обрали курс: %s → урок: %s → файл: %s\n",
    confirm_1 = "1) Підтвердити\n2) Вийти без змін\n",
    confirm_choice = "Ваш вибір: ",
    exit_restore = "Вихід без змін (відновлено попередній стан).\n",
    activated = "\n✅ %s → lesson.yaml (активуємо)\n",
    active_left = "✅ %s залишено як -ACTIVE.yaml\n",
    others_disabled = "✅ Всі інші .yaml файли перейменовано з суфіксом -DISABLED.yaml\n",
    swirl_update = "\nЩоб зміни застосувались у swirl, потрібно оновити встановлений курс.\n",
    swirl_update_now = "1) Оновити курс зараз\n2) Не оновлювати\n",
    swirl_update_choice = "Ваш вибір: ",
    swirl_updated = "✅ Курс '%s', урок '%s' оновлено у swirl!\n",
    swirl_copy_warn = "⚠️ Не всі файли вдалося скопіювати. Перевірте права доступу.\n",
    swirl_no_update = "ℹ️ Зміни застосовано лише у локальній копії. Щоб бачити їх у swirl, треба оновити курс вручну.\n",
    full_translation_ok = "✓ Повна українізація активована!\n",
    full_translation_fail = "❌ Помилка активації повної українізації: ",
    keep_original = "\n⏩ Залишено оригінальні фрази та інтерфейс swirl.\n",
    demo_title = "\n📋 ДЕМОНСТРАЦІЯ ФРАЗ / PHRASES DEMONSTRATION\n",
    demo_sep = paste(rep("-", 50), collapse=""),
    demo_praise = "Фрази похвали (Praise phrases):\n",
    demo_try_again = "\nФрази 'спробуй ще раз' (Try again phrases):\n",
    test_title = "\n🧪 ТЕСТУВАННЯ / TESTING\n",
    finish_ua = "\n🎉 УКРАЇНСЬКА МОВА АКТИВОВАНА! 🎉\n",
    swirl_start = "📚 Тепер запусти swirl() для початку курсу:\n\n    swirl()\n\n",
    commands = paste0(
      "💡 Корисні команди:\n",
      "    info_fun()                            # показати всі доступні функції\n",
      "    change_lesson_interactive()           # змінити активний YAML-файл уроку\n",
      "    activate_ukrainian_phrases_only()     # активувати тільки українські фрази\n",
      "    activate_ukrainian_full_translation() # активувати повну українізацію\n",
      "    deactivate_ukrainian_translation()    # повернути стандартний англійський swirl\n",
      "    check_ukrainian_status()              # перевірити статус перекладу\n",
      "    quick_activate()                      # швидка активація\n",
      "    quick_test()                          # швидкий тест фраз\n",
      "    activate(demo=TRUE)                   # показати демо\n",
      "    install_course_interactive()          # встановити курси інтерактивно\n",
      "    delete_course_interactive()           # видалити курси інтерактивно\n",
      "    update_course_interactive()           # оновити курси інтерактивно\n",
      "    reset_activate()                      # дозволяє запустити activate() ще раз за сесію\n",
      "    quick_restart_activate()              # перезапускає активацію\n",
      "\n🚀 Для старту swirl виконайте:\n    swirl()\n\n"
    ),
    swirl_run_prompt = "\nЗапустити swirl?\n1) Так\n2) Ні\n"
  ),
  en = list(
    start = "🇺🇦 Activating Ukrainian language for swirl... 🇺🇦\n\n",
    available_options = "\nAvailable options?\n",
    option_continue = "1) Continue\n",
    option_install = "2) Install\n",
    option_delete = "3) Delete\n",
    option_update_installed = "4) Update installed course\n",
    enter_choice = "Enter number (1/2/3/4) and press ENTER: ",
    enter_choice_simple = "Enter number and press ENTER: ",
    delete_prompt = "Do you want to remove local swirl courses?\n",
    yes = "1) Yes\n",
    no_continue = "2) Return\n",
    no_courses = "ℹ️ No local courses found.\n",
    select_delete = "\nSelect a course to remove:\n",
    continue = "Return",
    deleted = "  🗑️ Removed course: ",
    invalid = "⛔ Invalid choice. Try again.\n",
    skip_delete = "⏩ Skipped course removal.\n",
    install_prompt = "\nDo you want to install a local swirl course?\n",
    yes_install = "1) Yes\n",
    no_install = "2) Return\n",
    random_install = "3) Install a random course\n",
    available_courses = "\nℹ️ Available courses from swirl-courses folder:\n",
    enter_number_or_manual = "Select a course number to install, %d for manual input, or %d for random course: ",
    manual_course = "Enter course name (name_of_course): ",
    random_course = "Install a random course",
    not_found = "No local courses found. Enter course name manually (name_of_course): ",
    not_found_folder = "No local swirl-courses folder found. Enter course name manually (name_of_course): ",
    installing = "\nℹ️ Installing course from directory: ",
    installed = "✓ Course '%s' successfully installed and loaded!\n",
    not_exist = "❌ Course directory '%s' does not exist!\n",
    install_next = "\nWhat would you like to do next?\n1) Install another course\n2) Return\n",
    packages_missing = "\n❗ Required packages not installed:\n   ",
    packages_action = "Choose an action:\n1) Install packages\n2) Continue without installing\n",
    packages_install_cmd = "\n📦 To install packages, run:\ninstall.packages(c(%s))\n",
    packages_next = "Type 'next()' after finishing package installation: ",
    packages_success = "✓ All required packages installed!\n",
    packages_skipped = "⚠️ Continuing without installing swirl packages.\nSome features may be unavailable.\n",
    swirl_loaded = "✓ swirl package loaded\n",
    swirl_not_installed = "❌ swirl package not installed, cannot continue!\n",
    translation_choose = "\nWhich translation version do you want to activate?\n1) Ukrainian phrases only\n2) Full Ukrainian translation\n3) Keep original (no translation)\n",
    translation_enter = "Enter number (1/2/3) and press ENTER: ",
    only_phrases = "\n🔄 Activating only Ukrainian phrases...\n",
    only_phrases_ok = "✓ Ukrainian phrases activated!\n",
    only_phrases_fail = "❌ Error activating Ukrainian phrases: ",
    full_translation = "\n🔄 Activating full Ukrainian translation...\n",
    full_translation_ok = "✓ Full Ukrainian translation activated!\n",
    full_translation_fail = "❌ Error activating full Ukrainian translation: ",
    keep_original = "\n⏩ Kept original swirl phrases and interface.\n",
    demo_title = "\n📋 PHRASES DEMONSTRATION\n",pick_course = "Select a course (only installed in swirl):\n",
    exit = "Exit",
    course_number = "Enter course number: ",
    invalid_course = "Invalid course selection",
    pick_lesson = "\nSelect a lesson (only installed in swirl):\n",
    lesson_number = "Enter lesson number: ",
    invalid_lesson = "Invalid lesson selection",
    not_found_local = "Local lesson copy not found: ",
    no_yaml = "No .yaml in the selected lesson\n",
    only_lesson_yaml = "This lesson only has lesson.yaml. No additional YAML files available for activation.\n",
    pick_yaml = "\nSelect a .yaml file to activate:\n",
    yaml_number = "Enter .yaml number: ",
    invalid_yaml = "Invalid yaml selection. Exiting with no changes.\n",
    confirm_selection = "\nYou selected course: %s → lesson: %s → file: %s\n",
    confirm_1 = "1) Confirm\n2) Exit with no changes\n",
    confirm_choice = "Your choice: ",
    exit_restore = "Exited with no changes (restored prior state).\n",
    activated = "\n✅ %s → lesson.yaml (activated)\n",
    active_left = "✅ %s left as -ACTIVE.yaml\n",
    others_disabled = "✅ All other .yaml files renamed with -DISABLED.yaml suffix\n",
    swirl_update = "\nTo apply changes in swirl, you need to update the installed course.\n",
    swirl_update_now = "1) Update course now\n2) Do not update\n",
    swirl_update_choice = "Your choice: ",
    swirl_updated = "✅ Course '%s', lesson '%s' updated in swirl!\n",
    swirl_copy_warn = "⚠️ Not all files could be copied. Check file permissions.\n",
    swirl_no_update = "ℹ️ Changes applied only to the local copy. To see them in swirl, update the course manually.\n",
    demo_sep = paste(rep("-", 50), collapse=""),
    demo_praise = "Praise phrases:\n",
    demo_try_again = "\nTry again phrases:\n",
    test_title = "\n🧪 TESTING\n",
    finish_ua = "\n🎉 UKRAINIAN LANGUAGE ACTIVATED! 🎉\n",
    swirl_start = "📚 Now run swirl() to start a course:\n\n    swirl()\n\n",
    commands = paste0(
      "💡 Useful commands:\n",
      "    info_fun()                            # show all available functions\n",
      "    change_lesson_interactive()           # change active YAML file for a lesson\n",
      "    activate_ukrainian_phrases_only()     # activate only Ukrainian phrases\n",
      "    activate_ukrainian_full_translation() # activate full Ukrainian translation\n",
      "    deactivate_ukrainian_translation()    # revert to standard English swirl\n",
      "    check_ukrainian_status()              # check translation status\n",
      "    quick_activate()                      # quick activation\n",
      "    quick_test()                          # quick phrase test\n",
      "    activate(demo=TRUE)                   # show demo\n",
      "    install_course_interactive()          # install courses interactively\n",
      "    delete_course_interactive()           # delete courses interactively\n",
      "    update_course_interactive()           # update courses interactively\n",
      "    reset_activate()                      # allow you to run activate() again in session\n",
      "    quick_restart_activate()              # restart activation\n",
      "\n🚀 To start swirl, run:\n    swirl()\n\n"
    ),
    swirl_run_prompt = "\nRun swirl now?\n1) Yes\n2) No\n"
  )
)
